### ISSUE TITLE
pf-bb-config app not compatible with Kernel lockdown mode

### ISSUE THREAD

**Issue by mcoquelin** [intel/pf-bb-config#1]
The pf-bb-confif app mmap's the PCI BARs via the device's sysfs,
which is incompatible with the Kernel lockdown feature which blocks this functionality:
https://elixir.bootlin.com/linux/latest/source/drivers/pci/proc.c#L251

To support Kernel lockdown mode, pf-config-app should also support accessing the BARs via VFIO.

**Comment by rpieczon** [comment]
Any update?

**Comment by nicolas-chautru** [comment]
this is supported on 22.03 using pf_bb_config using vfio-pci from PF
