### ISSUE TITLE
Display the current configuration whether it's 4G, 5G, or both supported by Intel® vRAN Dedicated Accelerator's PF (Physical Function)

### ISSUE THREAD

**Issue by invicta198** [intel/pf-bb-config#16]
Currently, DPDK and intel/pf-bb-config don't offer a way to determine if a PF is set up with 4G or 5G configurations. The only reliable method at the moment is to use the DPDK test-bbdev utility. 
For instance, if a device is configured for 4G using pf_bb_config, trying to run tests with LDPC test data via test-bbdev would result in a **No suitable devices found!** Error. Similarly, attempting to run tests with Turbo test data on a device configured for 5G would also result in the same error.

To address this challenge, a proposed solution is to introduce a new command, such as `./pf_bb_config DEVICE_NAME [-s, --status]`, to provide an overview of the current device configuration.

**Comment by nicolas-chautru** [comment]
This is provided by pf_bb_config log.
