### ISSUE TITLE
No check about configure_device() return

### ISSUE THREAD

**Issue by dkoerich-wr** [intel/pf-bb-config#2]
In the current implementation of pf-bb-config, the calls to `configure_device()` do not check the error code (-1) when it gets failed. Therefore, the execution of pf-bb-config ends with 0 ("success") regardless of the device being or not properly configured. In an automated script that relies only on the return of pf-bb-config, it might lead to continuing with the device in unexpected configuration.

**Comment by nicolas-chautru** [comment]
should be resolved alredy
